### ISSUE TITLE
Error installing package in Arch linux.

### ISSUE THREAD

**Issue by DhimanAirao** [ros-noetic-arch/ros-noetic-qt-gui-cpp#5]
Hello, I am installing the ros-noetic full desktop on my Arch Linux, and `ros-noetic-qt-gui-cpp` package is not getting installed. It shows the error shown in the below figure.

versions installed in my system are as below:

python-pyqt5 5.15.10-1
python-pyqt5-sip 12.13.0-1
python-sip4 4.19.25-5
sip4 4.19.25-5

![screenshot-1698234976](https://github.com/ros-noetic-arch/ros-noetic-qt-gui-cpp/assets/39194002/63097a71-5492-4c4b-8b6b-055a70d40237)

**Comment by acxz** [comment]
```
sip: Deprecation warning: qt_gui_cpp.sip:1: %Module version number should be specified using the 'version' argument
sip: /usr/lib/python3.11/site-packages/PyQt5/bindings/QtCore/QtCoremod.sip:23: syntax error
Traceback (most recent call last):
  File "/opt/ros/noetic/share/python_qt_binding/cmake/sip_configure.py", line 123, in <module>
    subprocess.check_call(cmd)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/sip', '-c', '/home/acxz/vcs/git/github/ros-noetic-arch/ros-noetic-qt-gui-cpp/src/build/sip/qt_gui_cpp_sip', '-b', '/home/acxz/vcs/git/github/ros-noetic-arch/ros-noetic-qt-gui-cpp/src/build/sip/qt_gui_cpp_sip/pyqtscripting.sbf', '-I', '/usr/lib/python3.11/site-packages/PyQt5/bindings', '-w', '-n', 'PyQt5.sip', '-t', 'Qt_5_15_11', '-t', 'WS_X11', 'qt_gui_cpp.sip']' returned non-zero exit status 1.
make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:103: sip/qt_gui_cpp_sip/Makefile] Error 1
make[1]: *** [CMakeFiles/Makefile2:478: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by acxz** [comment]
Sorry about this issue @DhimanAirao, should be fixed now with the update to `ros-noetic-python-qt-binding`. I'll close this for now, just comment if you still have issues and I'll open this issue back up again.
